# Master playbook
# Notes:
# - Taints are applied only after monitoring tools have been installed on the pods.

# Console
- import_playbook: playbooks/kernel.yml
- import_playbook: playbooks/packetmanager.yml
- import_playbook: playbooks/datashare.yml
- import_playbook: playbooks/prereg.yml
- import_playbook: playbooks/regproc.yml
- import_playbook: playbooks/ida.yml
- import_playbook: playbooks/idrepo.yml
- import_playbook: playbooks/pms.yml
- import_playbook: playbooks/resident.yml
- import_playbook: playbooks/admin.yml
- import_playbook: playbooks/print.yml
- import_playbook: playbooks/mock-abis.yml
- import_playbook: playbooks/mock-mv.yml
# Regclient downloader
- import_playbook: playbooks/reg-client-downloader.yml
